Personal glömde bromsen - rullstol välte


Vård. En patient vid ett vård- och omsorgsboende i Eskilstuna välte med rullstolen efter att personalen glömt att lägga i bromsen.

Rullstolen kom i rullning och välte över en trottoarkant, skriver Eskilstuna-Kuriren.

Personen i rullstolen skadade bland annat armen och fick föras till sjukhus för vård.

Händelsen, som skedde i somras, har anmälts och utretts enligt lex Sarah.

TT
