Påse spärrade av Sturup


Brott. Polisen spärrade av på Sturups flygplats i Skåne efter att en misstänkt kvarglömd påse hittades. Men innehållet visade sig vara helt ofarligt.

– Det var inget speciellt i den här påsen, händelsen avslutad och klar och avspärrningarna är hävda, säger Åsa Emanuelsson, presstalesperson på polisen i region Syd.

Påsen hittades utomhus och varken flyg- eller biltrafik påverkades av polispådraget. Larmet kom in klockan 12.41 och 14.46 hävdes avspärrningarna.

TT
