Äldre kvinna död i villabrand


Bränder. En äldre kvinna avled efter en villabrand i Färila i Ljusdals kommun. Larmet om branden kom in vid 15-tiden på torsdagen.

– Det var begränsat till den övre våningen, säger Leif Gäfvert, insatsledare vid räddningstjänsten, till Expressen.

Hur branden startade är oklart men det finns ingen misstanke om brott.

Kvinnans anhöriga är underättade om dödsfallet.

TT
