Jägare allvarligt skadad av vildsvin


Olycka. En eftersöksjägare är allvarligt skadad efter att ha blivit attackerad av ett vildsvin i anslutning till väg 534 vid Hackvad utanför Örebro.

Den 43-årige jägaren hade i uppdrag att spåra vildsvinet efter en trafikolycka och när han kom till platsen för olyckan angrep djuret mannen som fick allvarliga skador med djupa sår i ett ben.

Vildsvinet hittades och sköts samma dag, skriver Nerikes Allehanda.

TT
