Boende dömd för asylbrand i Småland


Brott. En man i 20-årsåldern döms till rättspsykiatrisk vård för att ha anlagt en brand på ett asylboende i Hultsfred i juni. Mannen, som själv bodde där, hade före branden sökt upp personalen och sagt att han ville ha vård av en läkare. När han nekades detta hotade han att sätta eld på boendet, vilket han också senare gjorde, rapporterar P4 Kalmar.

Elden, som anlades i en garderob, kunde släckas av personalen, har lokala medier tidigare rapporterat. En anställd fick föras till sjukhus efter att ha andats in rök. Den rättspsykiatriska undersökningen visade att mannen begick brottet under påverkan av allvarlig psykisk sjukdom. Han har nekat till brottet.

TT
