Sex års fängelse för narkotikasmugglare


Brott. Ett par försökte resa in i Sverige med sex kilo heroin och fyra kilo kokain gömt i ett lönnutrymme i bilen. Men de stoppades av misstänksamma tulltjänstemän i Helsingborg och nu har mannen dömts till sex års fängelse, rapporterar Helsingborgs Dagblad. Även kvinnan var åtalad och satt nio månader i häkte före rättegången, men hon frias av Helsingborgs tingsrätt. Mannen däremot förklaras skyldig till synnerligen grov narkotikasmuggling och döms utöver fängelsestraffet till 15 års utvisning.

TT
