Man sköts i benet utanför Laholm


Brott. En person har skottskadats i benet i halländska Veinge, norr om Laholm. Den misstänkte gärningsmannen lämnade snabbt brottsplatsen och har inte gripits.

Den skottskadade var vid medvetande när han eller hon fördes till sjukhus. Skjutningen utreds som dråpförsök, uppger polisen på sin sajt.

Polisen genomför en teknisk undersökning av platsen där den skjutne hittades.

TT
