Förare kastades ur fordon - allvarligt skadad


Olyckor. En person har fått allvarliga skador efter en trafikolycka på gamla riksväg 40 i Borås. Föraren kastades ur bilen.

– Personen befann sig utanför bilen när vi kom fram, säger Joakim Mattsson vid Södra Älvsborgs räddningstjänstförbund till Borås Tidning.

Ett 15-tal brandmän och en ambulanshelikopter kallades till olycksplatsen och den skadade är förd till sjukhus. Vägen stängdes inledningsvis av men kunde öppnas igen vid 17.20-tiden.

TT
