Man skottskadad i Norrköping


Brott. En man skottskadades på onsdagskvällen i Norrköping, skriver NT. Sjukhuset ringde till polisen strax efter klockan åtta sedan mannen sökt vård.

– Den här personen är välkänd av oss sedan tidigare och är inte intresserad av att prata med oss, säger Torbjörn Lindqvist, vakthavande befäl vid polisregion Öst, till TT.

Skjutningen, som utreds som grov misshandel, ska ha skett i området Hageby. Mannen hade en skottskada i underkroppen.

TT
