Bil voltade - tre till sjukhus


Olyckor. Tre personer har förts till sjukhus sedan bilen de färdades i voltade av vägen.

– De har kört in i ett räcke på sidan av vägen in mot Kalmar. Sedan har de voltat ner i diket och hamnat på en cykelväg. Polisen får reda ut vad som har hänt, säger Daniel Åström, yttre befäl vid räddningstjänsten i Kalmar, till Barometern.

Det är oklart om personerna är allvarligt skadade. Olyckan inträffade strax efter klockan halv ett natten till lördagen.

TT
