tisdag 22 augusti 2017
Hela Gotland drabbat av strömavbrott


Olyckor. Gotland har drabbats av ett strömavbrott, som berör hela ön, skriver lokala medier. Gotlands energi arbetar med att lokalisera felet.

– Vi vet inte vad felet beror på. När det blir avbrott över hela Gotland brukar det ta 40 till 45 minuter innan strömmen är tillbaka om allt fungerar som det ska, säger Björn Axelsson, elnätschef vid Geab, till helagotland.se.

TT
