Narkotikabrott upptäckt vid inbrottslarm


Brott. Två män i Jönköping har anhållits misstänkta för narkotikabrott. De hittades i anslutning till en odling som kan användas för framställning av narkotika, uppger polisen.

Odlingen och männen hittades i ett skogsområde av poliser som åkte till platsen efter att ett inbrottslarm utlösts på ett företag i närheten, skriver SVT Nyheter Jönköping.

Männen är 35 och 55 år gamla. Händelsen utreds som brott mot narkotikastrafflagen.

TT
