Förare kastades ur fordon - allvarligt skadad


Olyckor. En person har fått allvarliga skador efter en trafikolycka på gamla riksväg 40 i Borås. Föraren ska ha kastats ur bilen.

– Personen befann sig utanför bilen när vi kom fram, säger Joakim Mattsson vid Södra Älvsborgs räddningstjänstförbund till Borås Tidning.

Ett 15-tal brandmän och en ambulanshelikopter har kallats till olycksplatsen. Vägen är avstängd.

TT
