Frias trots amfetamin i urinen


Brott. Kroppsbyggaren såg narkotikapåverkad ut, ansåg en polispatrull han mötte, och det urinprov han fick lämna visade spår av amfetamin. Ändå friades han av Lunds tingsrätt, där han åtalats för ringa narkotikabrott.

Domstolen tog fasta på att han äter många kosttillskott och att han därför ovetandes kan ha fått i sig amfetamin. Det räcker inte att mannen varit oaktsam i sin användning av utländsk medicin för att döma honom för ringa narkotikabrott, skriver domstolen.

Det är välkänt att kosttillskott som finns utomlands kan innehålla amfetamin utan att det står på förpackningen, hävdade mannen i rätten. Nu hade han nyligen varit i både Albanien och Dubai och köpt kosttillskott. Domstolen anser att det inte är bevisat att han hade uppsåt att begå brott, rapporterar SVT Nyheter Skåne.

TT
