Flicka misshandlad av man


Brott. En 15-årig flicka har förts till sjukhus efter att ha misshandlats av en man på en ort i Gällivare kommun, skriver Norrbottens-Kuriren.

Misshandeln skedde på onsdagseftermiddagen.

– Det var tydligt att våld hade utövats mot flickan, säger jouråklagaren Pontus Henriksson till tidningen.

Den 25-årige mannen är anhållen och brottet utreds som misshandel i nära relation.

TT
