Bil skadades i explosion


Brott. En bil blev delvis förstörd av en sprängladdning i Malm under natten till lördagen. Explosionen inträffade på Lorensbergsgatan strax efter klockan tre.

– Jag vet inte mycket mer om ärendet än att tekniker håller på att titta på den här bilen. Jag vet inte hur vi kommer att rubricera det här ännu, säger Mikael Lind, vakthavande befäl i polisregion Syd till Sydsvenskan.

Ingen person har skadats.

TT
