Flicka anhållen för inblandning i flera brott


Brott. En 17-årig flicka har anhållits för inblandning i ett fall som handlar om människorov, grovt rån, försök till grov utpressning, övergrepp i rättssak och brott mot vapenlagen i centrala Malmö, skriver Sydsvenskan.

Hon misstänks för medhjälp till ett par av brotten. Fler inblandade jagas.

Även en 19-årig man är anhållen för brotten, som har utförts mot en man i 30-årsåldern.

Polisen är i övrigt förtegen.

TT
