Supporter åtalad för bengaliska eldar


Brott. En 17-årig fotbollssupporter åtalas för att ha tänt bengaliska eldar när han var på väg mot en allsvensk match i Halmstad i juli. Han var maskerad, men en polis följde honom med blicken ända tills han tog av sig sin rånarluva.

Han åtalas för framkallande av fara för annan, brott mot ordningslagen och brott mot lagen om brandfarliga och explosiva varor. Utöver en dom i tingsrätten riskerar han även tillträdesförbud till framtida matcher, rapporterar SVT Nyheter Halland.

TT
