Skadad troligen skjuten med luftvapen


Brott. En skadad man påträffades i Helsingborg sent på tisdagseftermiddagen. Mannen, som sagt att han blivit skjuten, fördes till sjukhus.

Polisen tror att mannen, i 65-årsåldern, har blivit skjuten med ett luftvapen och skadorna beskrivs inledningsvis som lindriga. Brottet rubriceras som misshandel, men rubriceringen kan eventuellt skärpas till grov misshandel, skriver polisen på sin sajt.

TT
