Två gripna efter knivmisshandel


Brott. Två personer har gripits efter en knivskärning i centrala Uppsala, skriver Upsala Nya Tidning.

En person knivskars i ansiktet på tisdagseftermiddagen. De misstänkta flydde sedan i en bil.

– Bilen hittas sedan dumpad, säger Johan Lindén, RLC-befäl vid polisregion Mitt, till UNT.

De gripna misstänks för grov misshandel, grovt vapenbrott, vårdslöshet i trafik och även någon form av utpressning.

TT
