Hot mot Hultqvist kvarstår


Politik. Alliansens misstroendehot mot försvarsminister Peter Hultqvist (S) kvarstår tills vidare. Det var ledarna för Alliansen överens om vid ett möte på tisdagen, enligt uppgift till TT. Något definitivt beslut har dock inte tagits.

Under mötet, som var inplanerat sedan tidigare, kom regeringens hantering av IT-skandalen på Transportstyrelsen upp. Att statsministerns statsekreterare Emma Lennartsson avgick i söndags och lämnade nya uppgifter om när hon informerades om IT-skandalen ändrar för närvarande inte Alliansens hot om att begära en misstroendeomröstning mot Hultqvist när riksdagen öppnar den 12 september.

TT
