Nio får dödades av hund


Brott. När nio får hittats döda i en hage i Älmeboda i södra Småland trodde ägaren att fåren rivits av en varg. Men nu har länsstyrelsens besiktningsman konstaterat att fåren dödades en av en eller möjligen två hundar. Fåren hade inte dödats omedelbart av hugg, utan av infektioner i sår som orsakats av bett. Eftersom det inte var vilda rovdjur som låg bakom fårdöden blir fallet nu ett polisärende, rapporterar P4 Kronoberg.

TT
