Elever ska kartlägga hösten


Miljö. När kommer hösten egentligen till Sverige, och var?

Det vill Sveriges lantbruksuniversitet, SLU, ha hjälp med att kartlägga, skriver Sveriges Radio P4 Norrbotten.

I projektet Höstförsöket, som har pågått sedan 2013, efterlyser SLU skolelever som kan hjälpa till med att kartlägga när trädens löv ändrar färg runt om i Sverige. Speciellt efterlyses fler deltagare från Norrbottens inland.

TT
