Fängelse - för klockstöld och vattenskador


Brott. En 29-årig man döms till tio månaders fängelse av Växsjö tingsrätt för flera stölder och skadegörelse, rapporterar P4 Kronoberg.

Från en guldsmedsaffär i Ljungby ska mannen ha stulit klockor och smycken och han ska även ha trängt sig in i en lägenhet i Ljungby för att försöka stjäla.

Inne på polisstationen i Ljungby tog mannen sönder en vattenledning och orsakade vattenskador. Han därför döms även för skadegörelse.

TT
