En svårt skadad i bilolycka


Olyckor. En person skadades allvarligt i en trafikolycka norr om Gävle under natten till söndagen, skriver flera medier.

– Bilen ska ha farit av vägen och kört in i en elstolpe och en mjölkpall innan den hamnade i diket, säger Tor Stens, vakthavande befäl vid polisregion Mitt, till Aftonbladet.

Föraren skadades svårt, medan en passagerare klarade sig med lindriga skador. Räddningstjänsten klippte upp taket för att få loss föraren.

TT
