Mc-förare svårt skadad i olycka


Olyckor. En motorcyklist har skadats i en kollision med en bil. Olyckan inträffade på väg 55 utanför Flen.

Mc-föraren fördes till Mälarsjukhuset i Eskilstuna. Sjukhuset meddelade senare att mannen är svårt skadad och att han skickas till ett annat sjukhus för vidare vård.

Även bilföraren fördes till sjukhus, men han är lindrigt skadad.

Olyckan skedde vid 16-tiden på måndagen.

TT
