Annie Lööf sommartalar i Stockholm


– Vi lever i en omvälvande tid. Det är en tid då värderingar spelar roll, inleder Centerpartiets partiledare Annie Lööf sitt sommartal på Djurgården i Stockholm.

Politik. Annie Lööf talar om en omvälvande tid där terrorister mördar oskyldiga och högerextrema hetsar och hatar, och att det kräver en kraftfull motståndsrörelse mot extremism.

– Stå upp, stå pall. Anständigheten behöver er, säger Annie Lööf.

TT
