Ung man knivskars i Trelleborg


Brott. En man i 25-årsåldern knivskars i Trelleborg på lördagskvällen. Han skadades vid en misshandel där flera personer var inblandade och fördes med ambulans till sjukhus, skriver Trelleborgs Allehanda.

Knivskärningen, som skedde vid halv åtta, utreds som försök till mord alternativt försök till dråp.

Ingen misstänkt är gripen, enligt vakthavande befäl i polisregion Syd.

TT
