Rättegång inleds om Stensjömordet


Brott. I dag inleds rättegången mot en man i 50-årsåldern som står åtalad för mord på en 46-årig släkting, rapporterar P4 Dalarna.

Den 46-årige mannen höggs ihjäl med en sax vid fiskesjön Stensjön utanför Falun i slutet av maj.

I förundersökningen framkom uppgifter om att 46-åringen i tidigare beordrats av släktingen att döda sina döttrar. Något som mannen vägrade att göra, enligt SVT Nyheterna Västmanland.

TT
