Explosion i Malmö i natt


Brott. En detonation utanför en biluthyrningsfirma i Rosengård i Malmö strax före midnatt orsakade skador i en entrédörr. Även tre bilar som stod i närheten skadades.

– Bombskyddsgruppen och polisens tekniker har varit på plats, men vad det är som har detonerat är för mig okänt, säger Maya Forstenius, presstalesperson vid polisens ledningscentral för Region Syd.

Polis ryckte ut till platsen då uppringare slagit larm om att de hört en hög smäll. Brottet rubriceras som grov skadegörelse.

TT
