Åtal för hot mot spel-vd efter pokerförluster


Brott. En man i Ronneby som förlorat stora belopp på nätpoker åtalas för att ha mejlhotat Svenska Spels vd. I mejlet, som skickades till bolagets kundtjänst, uppmanades vd:n bland annat att "gå under jorden för sitt eget bästa", rapporterar Sydöstran.

Hotet skickades förra hösten. Då hade den åtalade förlorat uppåt 60 000 kronor på spel och misstänkte att det berodde på att andra som deltog i spelet fuskade, enligt åklagaren. Den åtalade mannen säger att han inte minns att han skickat hotet och att det skedde under en period då hans liv var kaotiskt. Svenska spels vd Lennart Käll har i polisförhör sagt att han tog illa vid sig av mejlhotet, särskilt eftersom han tidigare varit utsatt för ett allvarligt brott.

TT
