Tre personer till sjukhus efter köksbrand


Brand. Tre personer har förts till sjukhus med rökskador efter en lägenhetsbrand i Malmö, skriver polisen i region Syd på sin hemsida.

– Något har brunnit på en spis. Det har gjorts försök att släcka det. Omständigheterna är lite oklara, säger Anna Göransson vid polisens ledningscentral till Sydsvenskan.

Vid 14-tiden uppgav polisen att branden har släckts, enligt tidningen.

TT
