Allt fler smiter från straff


Brott. Allt fler smiter från sina fängelsestraff och får dem preskriberade efter att ha hållit sig undan tillräckligt länge. Bara de senaste tre åren handlar det om över 300 personer, rapporterar Ekot, Sveriges Radio.

Vid straff kortare än ett år preskriberas det efter fem år, vid längre straff är preskriptionstiden längre.

– Det kan ju uppfattas som ett hån ur brottsofferperspektiv, säger Brottsofferjourens ordförande Sven-Erik Alhem till Ekot.

TT
