Två skadade efter vansinnesfärd i Malmö


Olyckor. En bil kraschade i en rondell i stadsdelen Lindeborg i Malmö efter att ha jagats av en polisbil på E6. Bilen körde rakt igenom rondellen och voltade.

De två personerna i bilen skadades, varav minst en allvarligt, och de är förda med ambulans till sjukhus, skriver Sydsvenskan.

Föraren misstänks för grov vårdslöshet i trafik och drograttfylla, uppger polisen för Kvällsposten.

TT
