Körde lastbil med amfetamin i kroppen


Brott. En man i 30-årsåldern i Sundsvall åtalas för att ha kört lastbil drogpåverkad, och dessutom utan behörighet för att framföra den typen av fordon, skriver Sundsvalls Tidning.

Han hade amfetamin i blodet när han ertappades av polis, enligt åtalet.

Åklagaren hävdar att mannen dessutom kört lastbil utan att ha behörighet flera gånger. Han åtalas därför för grov olovlig körning, utöver drograttfylleri och narkotikabrott.

TT
