En påkörd i Vilhelmina - misstänkt mordförsök


Brott. En person har blivit påkörd av en bil i Vilhelmina, skriver polisen på sin hemsida. Personen har förts till sjukhus med måttliga skador, skriver flera medier.

Polisen misstänker att påkörningen var avsiktlig och att den kan ha ett samband med ett bråk mellan flera personer i området. Händelsen rubriceras som mordförsök.

Larmet om påkörningen kom vid fyratiden på torsdagsmorgonen. Ett villaområde har spärrats av.

TT
