Tjuv stal oanvändbara pengar


Brott. En 91-årig man i Fagersta fick ett samtal på tisdagskvällen om att en sjuksköterska skulle komma och kontrollera hans mediciner.

Sent på kvällen ringde hon på, men han anade oråd när han blev utmotad i köket och larmade därför hemtjänsten.

När kvinnan lämnade lägenheten såg 91-åringen även en man springa därifrån, enligt polisen i Västmanland. Mannen hade stulit en plånbok. Den innehöll tre äldre hundrakronorssedlar, som inte går att använda.

TT
