Avled efter olycka på utflykt


Omsorg. En rullstolsburen person avled efter att ha skadats vid en utflykt som anordnades för olika vård- och omsorgsboenden i Nynäshamn under sommaren, skriver Nynäshamns-Posten.

Sex personer med rullstol skulle ha varsin ledsagare, men en ledsagare kom senare. Gruppen började gå och en av de rullstolsburna tog sig fram själv och rullstolen välte.

Personen avled av följdskadorna, enligt en lex Sarah-anmälan till Inspektionen för vård och omsorg.

TT
