Orkanen stoppar NFL-premiär i Miami


Amerikansk fotboll. Orkanen Irma väntas nå södra Florida till helgen. Därför har amerikanska fotbollsligan NFL beslutat att premiärmatchen mellan Miami Dolphins och Tampa Bay Buccaneers inte kan spelas som planerat.

I ett uttalande säger NFL att det av säkerhetsskäl inte är lämpligt att spela i södra Florida med tanke på det aktuella nödläget. Det är oklart om matchen kommer att spelas på annan ort på söndag, eller om den avgörs i Miami senare under säsongen.

TT-Reuters
