Kevin Anderson till final i US Open


Tennis. Sydafrikanen Kevin Anderson har vunnit semifinalen i US Open genom att slå ut tolfterankade spanjoren Pablo Carreño Busta med siffrorna 4-6, 7-5, 6-3, 6-4.

Anderson är rankad 28:a i världen och kommer att spela final natten mot måndag svensk tid.

Vem Anderson får möta då är inte klart. Under natten spelar Rafael Nadal och Juan Martín del Potro om den andra finalplatsen.

TT
