Larsson utslagen ur US Open-dubbeln


Tennis. Johanna Larsson har spelat klart i US Opens dubbelturnering. I par med nederländskan Kiki Bertens blev det förlust mot Lucie Hradecka och Katerina Siniakova i den tredje omgången. Den heltjeckiska tennisduon tog kommandot omedelbart och vann enkelt, 6-1, 6-3, på lite drygt en timme.

Mindre än ett dygn tidigare tog sig Larsson och Bertens vidare från andra omgången genom att slå amerikanskorna Julia Boserup och Nicole Gibbs med siffrorna 6-2, 6-3.

TT
