Knivskars i magen - en gripen för dråpförsök


Brott. En man har blivit knivskuren i magen i Solna norr om Stockholm. Han har förts till sjukhus och det är inte känt hur svåra skadorna är. En person är gripen och polisen har inlett en förundersökning om försök till dråp, enligt Stockholmspolisens webbplats.

En bostad i området Råsunda har undersökts av polisens tekniker och dörrknackning har genomförts.

Larmet kom in till polisen klockan 18.

TT
