Dyrt att dra högljudda svanar till rätten


Miljö. Efter att en kvinna i Borås störts av högljudda sångsvanar utanför huset drog hon fallet till mark- och miljödomstolen. Det blev dyrt för henne. Hos ska betala rättegångskostnader på 88 300 kronor enligt domen som nu kommit, skriver Borås Tidning.

Förra året gjorde miljökontoret i Borås stad ljudmätningar i området sedan kvinnan under flera år klagat över det höga ljudet från svanarna i Ramnasjön. Mätningarna visade att ljudet överskred godkända nivåer och en ny vak och foderplats gjordes i andra änden av sjön för att lösa problemet. Men kvinnan nöjde sig inte utan tog fallet till mark- och miljödomstolen i Vänersborg som nu alltså avgjort ärendet.

TT
