Hemtjänstpersonals gruppchatt anmäls


Samhälle. Nio hemtjänstanställda i Mora hade en stängd chatt-grupp på Facebooks meddelandetjänst Messenger, där kränkande och utlämnande bilder och kommentarer om vårdtagare delades.

Nu anmäler kommunen saken till Inspektionen för vård och omsorg, Ivo, enligt lex Sarah, skriver SVT Nyheter Dalarna.

Fyra personer har sagts upp efter att händelserna uppdagades i juni i år och agerandet är sedan tidigare polisanmält.

TT
