UD avråder från Nordkorearesor


Politik. Utrikesdepartementet har beslutat att avråda från icke nödvändiga resor till Nordkorea. Beslutet fattades på fredagen och meddelas på Regeringskansliets hemsida.

Läget på Koreahalvön är spänt till följd av den nordkoreanska regimens provsprängningar av kärnvapen och uppskjutningar av ballistiska robotar, vilket fått världssamfundet att reagera starkt.

Nordkorea är en repressiv enpartistat och ett av världens mest slutna länder.

TT
