Utrymning vid brand i bostadshus


Brand. Räddningstjänsten trodde att en torktumlare hade exploderat och orsakat en brand i ett flerfamiljhus i Mullsjö, väster om Jönköping. Men det visade sig vara en mindre brand i ett källarförråd som gjorde att rök spred sig i fastigheten, skriver SVT Jönköping.

Polisen misstänker att branden är anlagd och utreder händelsen som misstänkt mordbrand. Sex lägenheter utrymdes under morgonen. Ingen person har skadats i händelsen.

TT
