Väpnat rån mot restaurang


Brott. En snabbmatsrestaurang i Järfälla utanför Stockholm har under kvällen rånats av tre personer. Två av rånarna hade "pistolliknande föremål" och en hade kniv, uppger polisen.

De tre tvingade till sig pengar och sprang från platsen. Polisen letade under kvällen efter gärningsmännen.

Två anställda på restaurangen misshandlades av gärningsmännen under rånet, men klarade sig med lindriga skador.

TT
