Enköpingsborna kan dricka vattnet igen


Samhälle. Vattnet i Enköpings kommun har bedömts som otjänligt sedan bakterier upptäcktes i dricksvattnet i augusti. Källan identifierades till en av brunnarna i Vånsjöbrons vattentäkt och boenden i Enköping, Grillby, Hjälsta, Säva och Örsundsbro har varit tvungna att koka sitt dricksvatten fram till i dag. Provsvar visar att vattnet nu går att dricka igen, men det finns risk för bakslag, skriver kommunen.

"Vi fortsätter ta prover lite tätare än vanligt, eftersom vi vet från andra kommuners erfarenheter att det finns en risk för bakslag. Att bli av med koliforma bakterier som funnits i ett vattenledningsnät är komplicerat. Det kan alltså ta tid innan problemet är löst för gott." skriver Enköpings kommun på sin hemsida.

TT
