Åtal för upprepad misshandel av sambo


Brott. En 28-årig man åtalas för grov misshandel och grov fridskränkning av sin sambo i Melleruds kommun i Västra Götaland. Enligt åtalet bröt mannen kvinnans arm när hon var gravid för några år sedan. Han anklagas också för att vid en rad tillfällen ha dödshotat och misshandlat henne, med sparkar, slag och tillhyggen. En gång slog han kvinnan med ett metallrör och en ihopfälld dockbarnvagn, enligt åtalet vid Vänersborgs tingsrätt.

Mannen nekar till brotten.

TT
