Flera ofredanden anmälda efter stadsfest


Brott. Polisen har fått in nio anmälningar om sexuella ofredanden under årets stadsfest i centrala Eksjö förra helgen.

Det finns inga uppgifter om åldern på de personer som ska ha utsatts för brotten, skriver Jönköpings-Posten.

– Jag kan inte kommentera det eller något annat nu, säger Fredrik Magnusson, vid polisen på Höglandet, till tidningen och hänvisar till förundersökningssekretess.

TT
