Nu är lex Maja verklighet


Djur. Riksdagen har röstat igenom en ny lagstiftning som gör det möjligt för vårdpersonal att anmäla misstänkt vanvård av djur utan att riskera att bryta mot tystnadsplikten, rapporterar Länstidningen i Södertälje.

Förslaget om en sådan lag kom till efter Södertäljekatten Majas tragiska öde.

Maja dog när hennes matte åkte in på sjukhus i juni 2016. Hemtjänsten slog inte larm om att katten var ensam med hänvisning till sekretessbestämmelser.

TT
