Rån i Blekinge fångades på film


Brott. En 23-årig man har häktats för det grova rånet i Mörrum i Blekinge i söndags, delvis tack vare film från en övervakningskamera, rapporterar SVT Nyheter Blekinge. På filmen kan man se hur en 70-årig man sätter sig i sin parkerade bil och hur den misstänkte sedan hoppar in i baksätet. Offret hotades sedan med ett pistolliknande föremål och tvingades att köra till en bankomat i Svängsta och ta ut flera tusen kronor som rånaren lade beslag på. Även vittnesuppgifter bidrog till att 23-åringen kunde gripas. Han har häktats som misstänkt för olaga tvång och grovt rån.

TT
