Kraftig brand i pappersbruk


Brand. Det brinner i ett pappersbruk i Karlsborg i Kalix kommun, och drygt 25 brandmän bekämpar branden, enligt lokala medier.

Larmet om brand i en hög byggnad vid pappersbruket kom vid 22-tiden, och det rör sig om en brand i ett gammalt blekeri. Stora delar av taket och väggarna har brunnit.

Polisen har spärrat av området vid fabrikens grindar på grund av explosionsrisken. Ingen människa har skadats, och det finns ingen spridningsrisk.

TT
