En anhållen efter olycka där barn miste livet


Olyckor. En kvinna har anhållits misstänkt för inblandning i en trafikolycka strax söder om Sundsvall där en pojke i tioårsåldern miste livet. Hon misstänks bland annat för vårdslöshet i trafik, vållande till kroppsskada, grovt vållande till annans död och olovlig körning, skriver Expressen.

Polis och räddningstjänst fick larm om olyckan vid 14.40 på söndagen. Pojken blev påkörd av en bil som voltade och landade på två bilar som stod parkerade vid en församlingslokal i Bredsand utanför Sundsvall. Han fördes till sjukhus men dog av sina skador.

TT
