Larm om överfallsvåldtäkt i Sundbyberg


Brott. Polisen har fått larm om att en kvinna blivit överfallen och våldtagen av en okänd gärningsman vid en gång- och cykelväg mellan Rissne och Kista i Sundbyberg, nordväst om Stockholm.

Larmet kom in strax efter 20 på fredagskvällen. Platsen är avspärrad i avvaktan på tekniker. Poliser letar efter gärningsmannen och en hundpatrull är på plats, skriver polisen på sin hemsida.

En förundersökning om våldtäkt har inletts.

TT
