Anställd misstänkt för sex med ensamkommande


Brott. En kvinna har stängts av från sin tjänst på ett boende för ensamkommande ungdomar i Skövde kommun då hon misstänks ha haft sex med flera av ungdomarna.

Det var då en av ungdomarna berättade att han haft sex med kvinnan flera gånger när hon var i tjänst som en lex Sarah-anmälan upprättades, uppger P4 Skaraborg. Enligt anmälan ska ungdomen ha sagt att kvinnan haft sex med flera på boendet.

En polisutredning pågår om fallet.

TT
