Avled efter frontalkrock med lastbil


Olycka. En man i 30-årsåldern avled efter att den personbil har körde frontalkrockat med en lastbil på riksväg 31/47 söder om Nässjö på morgonen, uppger polisen. Personbilen blev mycket kraftigt demolerad och både föraren i personbilen och lastbilen klämdes fast och fick klippas loss.

Närmaste anhöriga är underrättade.

Polis och räddningstjänst spärrade av vägen och olyckan orsakade långa köer på förmiddagen.

TT
