Sköt i luften vid poliskontroll


Brott. En person sköt flera skott i luften i samband med en poliskontroll i Fisksätra öster om Stockholm. Skotten riktades inte mot någon i polispatrullen.

– I samband med kontroll av några personer på plats så är det en person som tar upp ett vapen, skjuter ett par skott i luften, säger Lars Byström vid polisens ledningscentral till Aftonbladet.

Skytten, som misstänks för grovt vapenbrott och framkallande av fara för annan, har inte gripits.

TT
