Så gick det sen för Filip & Fredrik-originalen
JONI NYKÄNEN

Så gick det för profilerna i ”100 höjdare”, ”Lite sällskap” och ”High chaparall”:

✓ Kämpar för att överleva

✓ Tyckte inte om Filip & Fredrik

✓ Misshandlad och hotad med pistol

✓ Får beundrarbrev från kvinnor

✓ ”Jag fick över 3000 vänner när jag var med i tv-serien”

✓ Ramlade och slog huvudet i en sten

✓ Kämpar öppet mot drogerna

✓ Förändrades efter resan till Asien
