Utrikes framtids-pm 7.9-8.10
TT-AFTONBLADET

Torsdag 7 september

Grekland: Frankrikes president Emmanuel Macron besöker Aten.

Tyskland: Europeiska centralbankens styrelse möts för att fastställa politik för euroområdet.

Storbritannien/Gibraltar: Medlemmar från franska Emmaus kommer att paddla kajak i Gibraltarsundet för att uppmärksamma de tusentals flyktingar och migranter som har drunknat i Medelhavet.

Storbritannien: Första parlamentariska debatten om lagförslaget hur EU-lag ska bli brittisk lag i och med utträdet ur unionen.

Storbritannien: 85-årige brittiska thrillerförfattaren John Le Carre publicerar sin senaste roman "Spionernas arv".

Storbritannien: Prins George, son till prins William, börjar skolan.

Mexiko: Nederländernas drottning Maxima på besök.

EU: Utrikesministrarna håller informellt möte i Tallinn (till 8/9). Utrikesminister Margot Wallström deltar.

Fredag 8 september

Ryssland: IMF-chefen Christine Lagarde i Moskva.

Ryssland: Utrikesminister Sergej Lavrov tar emot sin franska kollega Jean-Yves Le Drian.

USA: Den tidigare kongressledamoten Anthony Weiner, som erkänt sig skyldig till att ha skickat sexbilder och sexmeddelanden till en 15-årig flicka, får sitt straff.

Kanada: Rättegången mot den misstänkte skytten i attacken mot en moské i Québec.

Lördag 9 september

Storbritannien: EU-anhängare demonstrerar i London.

Storbritannien: Manchester Arena öppnar för första gången sedan den dödliga attacken i maj, med en välgörenhetskonsert med Noel Gallagher från Oasis.

Söndag 10 september

Polen: Förre georgiske presidenten Mikhail Saakashvili planerar att korsa gränsen till Ukraina i Korczowa, Polen, trots att han har fråntagits sitt medborgarskap av Ukrainas president Petro Porosjenko.

Måndag 11 september

Spanien: Stora demonstrationer till stöd för självständighet väntas när Katalonien firar sin nationaldag.

Tyskland: Förbundskansler Angela Merkel deltar i tv-utfrågning inför förbundsdagsvalet.

Schweiz: FN:s råd för mänskliga rättigheter inleder sitt höstmöte (till 29/9).

Israel: Experter och tjänstemän deltar i konferens mot terrorism i Herzliya (till 12/9).

Turkiet: Nya utfrågningar i rättegången mot journalister från den oppositionella tidningen Cumhuriyet som står anklagade för att stödja "terroristgrupper".

Tyskland: Förbundskansler Angela Merkel frågas ut i tv-kanalen ARD inför valet den 24 september.

Norge: Val till stortinget.

EU: Parlamentet håller session i Strasbourg (till 14/9).

EU: Biståndsministrarna håller informellt möte i Tallinn.

Tisdag 12 september

Argentina: Israels premiärminister Benjamin Netanyahu i Buenos Aires (till 13/9).

Storbritannien: Den internationella försvarsindustrimässan DSEI i London, försvarskoncernen Saab deltar med senaste uppdateringarna om Gripen-plan.

USA: Hillary Clinton släpper sin bok med titeln "What Happened" (Det som hände) om hennes kamp mot Donald Trump i fjolårets presidentval.

Frankrike: Fackliga protester mot de arbetsreformer som presenterats av president Emmanuel Macron.

Israel: Israels förre premiärminister Shimon Peres memoarer, som färdigställdes några veckor före hans död, släpps.

USA: President Donald Trump tar emot Malaysias premiärminister Najib Razak i Vita huset.

Onsdag 13 september

Peru: Frankrikes president Emmanuel Macron på besök inför Internationella olympiska kommitténs beslut om värdstäder för sommar-OS 2024 och 2028.

EU: Kommissionsordförande Jean-Claude Juncker håller sitt årliga tal om läget i unionen.

Torsdag 14 september

EU: Justitie- och inrikesministrarna möts i Bryssel.

Tyskland: Frankfurts bilsalong öppnas (till 24/9).

Storbritannien: Mercurypriset för årets musikalbum i Storbritannien.

Ryssland/Vitryssland: Stor gemensam militärövning inleds.

Fredag 15 september

USA: Före detta Beatlesmedlemmen Ringo Starr släpper soloalbum.

EU: Finansministrarna håller informellt möte i Tallinn (till 16/9).

EU: Euroländernas finansministrar möts i Tallinn.

USA: Nasas Cassini-uppdrag, som är på jakt efter oceanvärldar i vårt solsystem, inleder sin slutliga nedstigning mot Saturnus.

Lördag 16 september

Italien: Dalai lama besöker Sicilien (till 21/9).

Söndag 17 september

USA: TV-priset Emmy delas ut.

Kina: Val i Macao.

Måndag 18 september

Spanien: Rättegång med kvinnan som hävdar att hon är Salvador Dalis dotter och där ett DNA-test ska avgöra frågan.

EU: Fjärde förhandlingsrundan om brexit inleds i Bryssel.

Ryssland: En rysk domstol inleder förhandling i ärende där Raoul Wallenbergs släktingar har stämt säkerhetstjänsten, en efterträdare till sovjettidens KGB, för att man inte får tillgång till dokument som kan bringa klarhet i den svenska diplomatens öde.

Ryssland: Rysk domstol inleder rättegång mot företag som varit inblandade i flytt av gasturbiner från Ryssland till Krimhalvön och som flyttades i strid med såväl försäljningskontrakt som EU:s regler.

USA: Organisationen C40 - Climate Leadership Group möts och diskuterar klimatförändringar.

Tisdag 19 september

FN: Generalförsamlingens allmänna debatt och högnivåmöte inleds (till 25/9).

EU: Energi- och transportministrarna håller informellt möte i Tallinn (till 21/9).

Torsdag 21 september

Japan: Tokyo Game Show i Chiba inleds (till 24/9).

Angola: Den nye presidenten João Lourenço svärs in.

Lördag 23 september

USA: Global medborgarfestival, med anledning av att FN:s generalförsamling debatterar, med Stevie Wonder och Green Day.

Nya Zeeland: Val till parlamentet.

Söndag 24 september

Tyskland: Folkomröstning om framtiden för Berlins Tegel-flygplats.

Tyskland: Förbundsdagsval.

Storbritannien: Labourpartiet håller partikonferens i Brighton (till 27/9).

Måndag 25 september

Norge: Nordens största miljöräddningsövning, Scope, där bland andra svenska Kustbevakningen deltar (till 29/9).

Storbritannien: Förhandsvisning med anledning av Turnerpriset, Storbritanniens mest prestigefulla utmärkelse för samtida konstnärer. Prisceremonin äger rum den 5 december.

Filippinerna: Asean har möte.

Tisdag 26 september

Storbritannien: Sothebys i London auktionerar ut The Vivien Leigh Collection, en samling från skådespelerskan Vivien Leigh som består av hennes personliga tillhörigheter.

Italien: G7:s industriministrar möts (till 27/9).

Onsdag 27 september

Thailand: Högsta domstolen meddelar dom mot tidigare premiärminister Yingluck Shinawatra, som i augusti flydde landet då hon skulle få sin dom.

Torsdag 28 september

Italien: G7:s vetenskapsministrar möts (till 29/9).

Fredag 29 september

EU: Stats- och regeringscheferna håller toppmöte om digitala frågor i Tallinn.

Lördag 30 september

Italien: G7:s arbetsmarknadsministrar möts (till 1/10).

Söndag 1 oktober

Spanien: Regionala ledningen i Katalonien vill hålla folkomröstning om självständighet.

Tyskland: Ny lagstiftning träder i kraft och par av samma kön får rätt att gifta sig.

USA: Före detta NFL-stjärnan OJ Simpson, som stuttit dömd för väpnat rån och kidnappning sedan 2008, friges.

Storbritannien: Det konservativa partiet Tory håller partikonferens (till 4/10).

Tisdag 3 oktober

Schweiz: Europeiskt-iranskt forum om handel och investeringar i Iran.

Fredag 6 oktober

Norge: Nobels fredspris tillkännages.

Till redaktionen: Ovanstående är en orientering om kommande kända händelser. Det innebär inget automatiskt löfte om bevakning.

TT Nyhetsbyrån
