En kamp mot klockan i Mexiko


Mexiko. Räddningsarbetare letar febrilt efter fler överlevande efter den kraftiga jordbävningen i Mexiko för mindre än ett dygn sedan.

Minst 59 människor har hittills bekräftats döda. Enligt president Enrique Peña Nieto har 46 människor omkommit i delstaten Oaxaca, 10 i Chiapas och 3 i Tabasco.

Samtidigt kommer uppgifter från olika myndighetskällor om att dödssiffran kan vara så hög som 80.

TT-AFP
