Ryska annonser lämnade till Mueller


USA. Facebook har lämnat över all information till den särskilde åklagaren Robert Mueller om de annonser som företaget sålt till en rysk så kallad trollfabrik i samband med presidentvalet i USA i fjol.

Mueller leder en utredning av Rysslands inblandning i det amerikanska presidentvalet.

Informationen som nu lämnats över inkluderar kopior av annonser och information om annonsernas köpare, enligt en anonym källa med insyn i ärendet.

TT-Reuters
