Storm slog till mot turistort


Mexiko. Minst tre människor har omkommit efter de kraftiga skyfall som stormen Lidia fört med sig i Mexiko. Området kring den populära turistorten Los Cabos har drabbats av översvämningar.

Två vuxna och ett barn omkom när de skulle ta sig över en flod, enligt räddningstjänsten.

Stormen har även förstört hus och vägar och orsakat elavbrott. Lidia drar nu vidare norrut över den mexikanska halvön Baja California. Uppemot 30 centimeter regn väntas.

TT-Reuters
