Ex-presidents son får fängelse


Honduras. Fabio Lobo, son till Honduras tidigare president Porfirio Lobo, har dömts till 24 års fängelse i en domstol i New York för narkotikasmuggling och försäljning av kokain i USA.

Domen ska ses som en varning till korrupta medlemmar av den politiska eliten i Latinamerika, enligt domaren Lorna Schofield.

Hon säger att Lobo har utnyttjat sina kontakter och missbrukat sin ställning för att försöka tjäna pengar på narkotikasmuggling.

TT-AFP
