Många döda i knivattack i Nigeria


Nigeria. 18 människor har dödats i Nigeria av vad som tros vara militanta islamister från Boko Haram.

Knivattacken, som skedde nattetid i samhället Bonki, är den senaste i en rad dödliga dåd i nordöstra Nigeria som terrorgruppen legat bakom.

Attackerna har blivit allt fler den senaste tiden. Före fredagens dåd hade minst 172 människor dödats sedan den 1 juni i år. Boko Haram har dödat minst 20 000 människor i Nigeria de senaste åtta åren.

TT-Reuters
