Nynazistiska brittiska soldater gripna


Storbritannien. Fyra personer, däribland soldater i aktiv tjänst, har gripits misstänkta för terrorbrott, meddelar Storbritanniens försvarsdepartement.

De gripna beskrivs som nynazister.

"Vi kan bekräfta att ett antal tjänstgörande militärer har gripits i enlighet med antiterrorlagar, för kopplingar till en förbjuden extremhögergrupp", heter det i en kommuniké.

TT-AFP
