Dödssiffran stiger i orkanen Irma


Karibien/USA. Hittills har sex människor bekräftats döda på den franska ön Saint-Martin, sedan orkanen Irma dragit in över området.

– Det här är inte den slutgiltiga dödssiffran. Det finns risk för ytterligare upptäckter, säger Eric Maire, talesperson för ögruppen Guadeloupe.

Frankrikes utrikesdepartement meddelade tidigare att två människor omkommit och att två skadats allvarligt på öarna Saint-Barthélemy och Saint-Martin.

TT-AFP
