Merkel vill inte ha Turkiet i EU


Tyskland/Turkiet. Tysklands förbundskansler Angela Merkel ska försöka stoppa Turkiets medlemskapsförhandlingar med EU, sade hon under valduellen med utmanaren Martin Schulz, med tre veckor kvar till valet.

– Faktum är att Turkiet inte borde bli medlem i EU, sade Merkel under debatten.

– Jag ska prata med mina kollegor (i EU) för att se om vi kan nå en gemensam ståndpunkt i detta så att vi kan avsluta medlemskapsförhandlingarna, tillade hon.

Merkels talesperson säger dagen efter debatten att frågan om ett turkiskt medlemskap inte kommer att debatteras i EU förrän efter det tyska valet den 24 september, men att Turkiet för närvarande inte är i stånd att bli medlem.

– Förbundskanslerns ord talar för sig själva, säger Steffen Siebert.

Samma tongångar hörs från EU-kommissionens ordförande Jean-Claude Juncker, vars talesperson säger att den turkiska regeringens agerande gör det "omöjligt" för landet att bli gå med i unionen. Men han betonar att ett beslut om att avbryta samtalen måste fattas av medlemsländerna.

Merkels utspel kommer sannolikt att förvärra den redan ansträngda relationen mellan de båda Natoallierade. Relationen mellan länderna har försämrats sedan Turkiets president Recep Tayyip Erdogans tillslag mot motståndare i efterdyningarna av ett misslyckat kuppförsök i juli förra året. Tolv tyska medborgare har även fängslats i Turkiet, vilket ytterligare spätt på osämjan.

En talesperson för Erdogan kallar de tyska utspelen för "attacker mot Turkiet/Erdogan" och avfärdar dem som ett utslag av populism.

Merkels uttalande kom efter att Schulz verkade överraska henne med att säga att han skulle jobba för att sätta stopp för Turkiets medlemskapsförhandlingar med EU om han väljs till förbundskansler i valet.

TT-AFP-Reuters
