Två gripna efter fynd av sprängmedel


Frankrike. Fransk polis har hittat gasflaskor och sprängämnet TATP i samband med ett tillslag mot en lägenhet i en förort till Paris.

Ingen person befann sig i lägenheten i Villejuif vid tillslaget. Men två personer har gripits, uppger en poliskälla.

Utredningen kommer att ledas av en åklagare specialiserad på terrorbrott.

TATP är relativt lätt att tillverka och har använts vid en rad terrordåd i Europa de senaste åren.

TT-Reuters
