EU tittar på hårdare sanktioner mot Nordkorea


EU/Nordkorea. EU förbereder hårdare sanktioner mot Nordkorea, enligt unionens utrikeschef Federica Mogherini. De tänkta åtgärderna är en del av världssamfundets försök att straffa regimen i Pyongyang för landets senaste kärnvapentest.

– De kommande dagarna kommer jag att lägga fram utökade EU-autonoma sanktioner för ministrarna att arbeta med, säger Mogherini vid ett utrikesministermöte i Tallinn.

TT-AFP
