En skrattande ledare med brutal agenda


Nordkorea. Kim Jong-Un var enligt den nordkoreanska mytologin ett underbarn som kunde hantera en pistol och prata sju språk vid tre års ålder.

Men mycket lite är känt om den verklige Kim - bakom diktaturens propagandafasad.

Det här är vad vi tror oss veta.

Född den 8 januari 1982, 1983 eller 1984 - det förstnämnda året tros ha valts för att bättre passa in i personkulten - blev Kim 2011 en av världens yngsta statsledare. Han tog då över ledarskapet i världens mest slutna stat efter fadern och diktatorn Kim Jong-Il, som officiellt föddes 40 år tidigare. Kim Jong-Uns farfar Kim Il Sung, som fortfarande formellt är president i Nordkorea, föddes enligt mytologin 70 år tidigare.

Den japanskfödda koreanska dansaren Ko Yong-Hi - faderns tredje fru - som tros ha avlidit i bröstcancer 2004 antas ha varit Kims mor.

Kim Jong-Un ansågs av analytiker vara ett oskrivet kort, en sårbar ledare som lätt skulle kunna bli utmanövrerad av andra personer inom ledarskiktet när han tillträdde. I stället inleddes ett brutalt styre med utrensningar inom maktapparaten, där till och med hans inflytelserika morbror Jang Song-Thaek avrättades efter anklagelser om landsförräderi.

Kim tros också ligga bakom giftmordet på halvbrodern Kim Jong-Nam - sedd som Nordkoreas framtida ledare innan han föll i onåd på grund av ett besök i Japan - i Malaysia tidigare i år.

Bilden kontrasterar mot tillrättalagda foton i statliga nordkoreanska medier där en skrattande eller kärvänligt leende Kim, inte sällan utdelar kramar vid besök i fabriker eller vid offentliga evenemang.

Men bakom leendet finns en brutal diktator som enligt människorättsorganisationer systematiskt och urskillningslöst fängslar, torterar och avrättar oliktänkande.

Som ung studerade Kim i en schweizisk privatskola, i Gümligen nära huvudstaden Bern, och därefter i militärakademien i Pyongyang. Studierna i Schweiz skedde under överseende av mostern Ko Yong-Suk och hennes man. Det var aldrig känt för skolpersonalen eller eleverna att Kim tillhörde den styrande familjen i Nordkorea. Klasskamrater har beskrivit honom som tillbakadragen, intresserad av skidåkning och en beundrare av actionhjälten Jean-Claude Van Damme, skriver nyhetsbyrån AFP.

– Han hade humor, kom överens med alla, även med de elever som kom från länder som var fienden med Nordkorea, har en av klasskamraterna berättat för tyska Welt am Sonntag.

Mostern, som hoppade av och flydde till USA 1998, har dock i The Washington Post beskrivit Kim som intolerant och med kort stubin. Han ska också ha gillat basket - så mycket att han sov med basketbollen i sin säng.

Basketintresset tycks Kim inte ha släppt. Den amerikanske basketstjärnan Dennis Rodman är en av få västerlänningar som träffat Kim i Nordkorea.

Inte mycket är känt om Kims närmaste familj. Men efter ett av Rodmans besök, 2013, avslöjade han för brittiska The Guardian att Kim hade en dotter: Kim Ju-Ae.

– Han är en bra pappa och har en bedårande familj, sade Rodman.

Då hade landets första dam Ri Sol-Ju bara varit känd för allmänheten i ett år. I slutet av augusti 2017 rapporterade den sydkoreanska underrättelsetjänsten att paret fått sitt tredje barn, skriver AFP.

Som tredje generationens ledare i Kimdynastin har Kim Jong-Un tagit full kontroll över statsapparaten - förra året utsåg han sig själv till ordförande i den nyinstiftade Högsta styrelsekommittén. Han har också drivit faderns konfrontativa hållning gentemot omvärlden till sin spets, med återkommande kärnvapen- och robottest.

Samtidigt har landet slutit sig än mer sedan Kims tillträde. Han har fjärmat sig även från Kina, som historiskt varit det närmaste en allierad landet har haft. Han har hittills inte besökt grannlandet för att träffa president Xi Jinping. Peking, som tidigare hållit Pyongyang under armarna, har å sin sida infört omfattande sanktioner mot Nordkorea.

Kim sägs ha vetat redan vid sin åttaårsdag att han skulle bli Nordkoreas ledare. I landets ibland bisarra mytologi, som präglas av personkulten kring familjen Kim, hade han då redan lärt sig köra bil och hantera en pistol. Liksom sin far och sin farfar upphöjs ledaren med hjälp av propaganda till en slags gud. Frågan är hur han uppfattas av landets befolkning.

– Det är inte så att människor är hjärntvättade och tror att han är Gud. Människorna vet vad det handlar om, men det vågar de inte utmana, säger den nordkoreanska avhopparen Jang Jin-Sung, enligt The Guardian.

TT
