Dammar öppnas för att rädda områden


USA. Myndigheterna i Houston i USA planerar att öppna luckor i överfyllda dammar och medvetet släppa ut vatten i vissa områden för att rädda centrala delar av staden.

Invånare i de västra delarna av mångmiljonstaden uppmanas att evakuera inför att vattet ska släppas på.

Vattenmassorna kommer att flöda ner mot upp till 20 000 bostäder, som redan översvämmats tidigare i veckan. Inga hus som klarat sig torrskodda i stormen Harvey ska drabbas.

TT-AP
