Trump avslutar migrantprogram


USA. USA:s president Donald Trump har bestämt sig för att avsluta ett program som ger arbetstillstånd till personer som kom till USA illegalt som barn, enligt två källor med insyn i frågan.

Trump kommer att ge kongressen sex månader på sig att ta fram ett alternativ till programmet som är känt som DACA.

Omkring 800 000 arbetstillstånd har godkänts enligt reformen som infördes 2012 under den tidigare presidenten Barack Obamas styre.

TT-Reuters
