Värsta skandalscenerna i ”Paradise hotel”
ZANDRA LUNDBERG

✓ Deltagarna har femkant i poolen

✓ Kokain på hotellet

✓ Skickades hem efter mobbning

✓ Hamnade i en stor knarkhärva

✓ Sexakten ”Eiffeltornet” introduceras

✓ Misshandlar varandra vid poolen

✓ Ligger med bästa vännens pojkvän

✓ Förlovade sig i programmet

✓ ”Jag tar vad jag vill ha – och sen är det bra”

✓ Gifte sig, skiljde sig, fick fängelse

✓ Gravidchock

✓ Triss i sex i poolen

.... och mer!
