”Gift vid första ögonkastet” – så gick det i andra länder
JONI NYKÄNEN

Så har det gått i Australien, Finland, Danmark, USA och Storbritannien:

✓ Tvingades söka psykologhjälp: ”Hade skett ett övergrepp”

✓ Klagade över att hustrun var ”sexuellt begränsad”

✓ Påkommen: Dejtade andra på Tinder

✓ Landet där två par skaffat barn

✓ Fick besöksförbud: Fruktade för sitt liv

Varför lyckas inte svenska ”Gift vid första ögonkastet”? Expertens tuffa besked till SVT.
