Flera saknas efter jordskred


Schweiz. Åtta människor saknas efter jordskred i Schweiz, rapporterar nyhetsbyrån AFP som hänvisar till polisen. De saknade är medborgare i Tyskland, Österrike och Schweiz.

Raset inträffade på onsdagen i Val Bondasca och har delvis begravt en by som heter Bondo, skriver tidningen Blick. Området ligger i kantonen Graubünden (Grigioni) i östra Schweiz.

Flera byar fick evakueras i samband med jordskredet, enligt AFP.

TT
