Knivman angrep poliser i London


Storbritannien. En knivman har gått till angrepp mot poliser vid Buckingham Palace i London, skriver flera medier.

Två poliser har skadats, skriver Reuters.

Metropolitan Police bekräftar på Twitter att polisen har gripit en man misstänkt för att ha attackerat polisen. Två poliser skadades lindrigt under gripandet av mannen, men inga andra personer har skadats.

Polisen är kvar på platsen.

TT
