Antonov tar över som rysk ambassadör i USA


Ryssland. Rysslands president Vladimir Putin har utsett Sergej Kisljaks efterträdare som ambassadör i USA. Han ersätts som väntat av vice utrikesminister Anatolij Antonov, meddelar Kreml.

Kisljak har varit en av huvudpersonerna i den rysshärva som överskuggat president Donald Trumps första tid vid makten, efter flera uppmärksammade möten med företrädare för Trumpkampanjen före valet.

TT-Reuters
