Beslag av giftigt tyskt äggpulver


Bulgarien. Två stora partier med tyskt äggpulver innehållande det giftiga bekämpningsmedlet fipronil har upptäcktes i Bulgarien. Det är samma medel som har orsakat att miljontals ägg och andra äggprodukter har förstörts eller dragits tillbaka från handeln i en rad europeiska länder.

Bulgariens livsmedelsmyndighet informerades tidigare i augusti av Tyskland om ett parti med 500 kilo äggpulver som innehöll fipronil. Ett andra lika stort parti, också det från Tyskland, upptäcktes under tisdagen.

TT-AFP
