Ytterligare 13 döda i Filippinerna


Filippinerna. Polisen i Filippinerna har dödat minst 13 personer i en ny nattlig räd i Manila, enligt uppgifter från vittnen och medier. Därmed har minst 80 personer dödats den här veckan i president Rodrigo Dutertes blodiga krig mot knarket.

I onsdags sade Duterte att det var bra att över 30 kriminella hade dödats i provinsen Bulacan i en räd.

– Låt oss döda 32 varje dag. Kanske kan vi därigenom minska det som plågar landet, sade han.

TT-Reuters
