Spaniendåden: Två gripna i Marocko


Spanien. Två män har gripits i Marocko, misstänkta för att ha haft någon typ av koppling till terrorgruppen i Barcelona.

En av de gripna har tidigare bott i Barcelona. Han misstänks ha kopplingar till terrorgruppen IS och ska ha planerat en attack mot den spanska ambassaden i Rabat, enligt tv-kanalen 2M.

En andra person greps i staden Oujda, men är invånare i spanska Ripoll, hemvist för flera av de misstänkta inblandade i de spanska dåden.

TT-Reuters
