Trumps svar på dåden: Sprider vandringssägnen


Spanien. Ledare från hela världen fördömer terrorn i Spanien och uttrycker sin medkänsla med offren och deras anhöriga.

Men en ledare sticker ut. USA:s president Donald Trump hänvisar till en vandringssägnen om hur en amerikansk general doppade kulor i grisblod för att stoppa islamistisk terror.

På Twitter uppmanar president Trump sina 36 miljoner följare att studera hur den amerikanska generalen Pershing ska ha satt stopp för islamistisk terror.

"Studera det den amerikanska generalen Pershing gjorde mot tillfångatagna terrorister. Det satte stopp för radikal islamistisk terror i 35 år", skriver presidenten.

Enligt flera medier berättade han historien om första världskrigsgeneralen även under sin presidentkampanj.

– Han tog 50 kulor och doppade dem i grisblod. Sen beordrade han sina män att ladda gevären och ställde upp 50 personer och de sköt 49. Till den femtionde personen sade han: gå tillbaka till ditt folk och berätta vad som hände här. Sedan hade de inte problemet på 25 år, sade Trump vid ett valmöte i South Carolina i februari förra året.

Men historien om hur generalen begått krigsbrott under sin tid som guvernör i Filippinerna har visat sig vara substanslös och det finns inga bevis på att general Pershing gjort det som Trump berättat, enligt bland annat Washington Post.

Innan Trump skrev om generalen fördömde han attentatet på Twitter: "Förenta staterna fördömer terrorattacken i Barcelona, Spanien, och kommer att göra vad som är nödvändigt för att hjälpa till. Var tuffa & starka, vi älskar er".

Statsminister Stefan Löfven lämnade ett skriftligt uttalande timmarna efter dådet i Barcelona i går, ett dåd som krävt minst 13 dödsoffer:

"Jag förfäras av att ännu en storstad i Europa drabbats av sorgen och oron efter ett befarat terrordåd. Mina tankar är med de vars anhöriga omkommit eller skadats och alla de som inte ännu fått kontakt med sina nära och kära."

Det spanska kungahuset fördömer attacken via ett inlägg på Twitter: "De är mördare, kriminella som inte kan terrorisera oss. Hela Spanien är Barcelona", skriver hovet.

Spaniens premiärminister Mariano Rajoy skriver i sin tur att "terrorister kommer aldrig att besegra ett enat folk."

Tysklands förbundskansler Angela Merkel kallar händelsen för en "motbjudande attack", och sänder budskap om solidaritet med Spanien.

Storbritanniens premiärminister Theresa May slår fast att "Storbritannien står upp mot terrorn tillsammans med Spanien". "Mina tankar är med offren för dagens fruktansvärda attack i Barcelona", skriver hon.

Också den franske presidenten Emmanuel Macron uttrycker solidaritet med Spanien efter händelsen.

"Vi fortsätter stå enade och beslutsamma", skriver han på Twitter.

Den ryske presidenten Vladimir Putin talar om ett "grymt och cyniskt brott". EU-kommissionens ordförande Jean-Claude Juncker sänder sina kondoleanser till de drabbade, till spanska folket och till Rajoy:

Den turkiske utrikesministern Mevlüt Cavusoglu fördömer den "avskyvärda terrorattacken" och från Vatikanen hälsar påve Franciskus att han ber för offren.

TT
