Putin på plats vid mästerskap i judo


Ryssland/Ungern. När Rysslands president Vladimir Putin besöker Ungern förenar han nytta med nöje. Förutom att träffa premiärminister Viktor Orbán passade den ryske presidenten på att delta vid invigningen av världsmästerskapen i judo, enligt Kreml.

Presidenten - som själv har svart bälte - är hedersordförande för det internationella judoförbundet IJF och har gett ut boken "Lär dig judo med Vladimir Putin". Han har beskrivit sitt intresse för kampsport som seriöst och säger sig särskilt uppskatta filosofin, kulturen, relationen med motståndaren och reglerna för strid.

TT
