Kabul: Raket slog ned på fotbollsplan


Afghanistan. En raket har slagit ned på en fotbollsplan i diplomatkvarteren i Afghanistans huvudstad Kabul. Explosionen föregicks av en varning och larmsignaler hördes från flera utländska beskickningar, men enligt polisen finns inga rapporter om att någon skulle ha skadats.

Några timmar efter incidenten - natten mot tisdagen svensk tid - skulle USA:s president Donald Trump annonsera sin framtida strategi för Afghanistan. Troligen öppnar Trump för att skicka ytterligare tusentals soldater till landet.

TT-AFP-Reuters
