Storbritannien skärper synen på näthat


Storbritannien. Hatbrott på nätet kommer att betraktas som lika allvarliga som de som sker offline i Storbritannien, enligt landets åklagarmyndighet. Med de nya riktlinjerna hoppas myndigheten att fler människor ska anmäla brott som sker på nätet samt att domstolarna ska överväga längre straff.

– Det här är ett underrapporterat brott. I bland känner människor att det är något som de bara måste stå ut med. Det är absolut inte fallet, säger chefsåklagare Alison Saunders till BBC.

TT-Reuters
