Fyra döda i explosion på varv i Sydkorea


Sydkorea. Fyra personer har dödats i en explosion i samband med byggandet av en oljetanker på ett skeppsvarv i Sydkorea. Enligt myndigheterna höll varvsarbetarna på att måla fartyget invändigt när explosionen, av okänd anledning, inträffade.

– Jag hörde en smäll och sedan såg jag rök från oljetankern, berättar ett ögonvittne för nyhetsbyrån Yonhap.

TT-AFP-Reuters
