Knivman greps vid Buckingham Palace


Storbritannien. En man beväpnad med en kniv har gripits av polis vid Buckingham Palace i London.

Turister noterade att mannen agerade konstigt och kontaktade polisen, skriver The Guardian.

Metropolitan Police bekräftar på Twitter att polisen har gripit en man misstänkt för att ha attackerat polisen och att två poliser skadades lindrigt under gripandet av mannen. Inga andra personer har skadats.

TT-Reuters
