Greps med sprängmedel vid sydstatsstaty


USA. En 25-årig man med sprängämnen har häktats efter att ha gripits vid en staty av en sydstatsmilitär i Houston i Texas.

Enligt åklagare i Texas har mannen häktats misstänkt för att ha försökt skada eller förstöra statyn av löjtnant Richard Dowling, som var en av sydstaternas befälhavare under det amerikanska inbördeskriget som pågick mellan 1861 och 1865.

Det var i lördags som 25-åringen greps efter att en vakt upptäckt honom sittande på knä invid statyn i Hermann Park i Houston. Enligt åklagarna hade mannen med sig två lådor med silvertejp och kablar plus en flaska med explosiv vätska.

Frågan om sydstatsmilitärernas statyer i USA är extremt känslig, särskilt efter händelserna i Charlottesville tidigare denna månad då myndigheternas beslut att flytta en staty av sydstatsgeneralen Robert  E Lee fick vita nationalister, nazister och andra högerextrema grupper att samlas till en protesmarsch i staden. I samband med att motdemonstranter protesterade mot marschen uppstod våldsamheter, och en bil körde rakt in i gruppen av motdemonstranter. En 32-årig kvinna dödades i bilattacken.

TT-AP
