USA om Nordkorea: Något allvarligt måste ske


Nordkorea. President Donald Trump upprepar att USA inte utesluter ett militärt svar efter Nordkoreas provskjutning av en robot över Japan.

"Världen har uppfattat Nordkoreas senaste budskap klart och tydligt", säger Trump i ett uttalande.

Regimen i Pyongyang har enligt Trump "visat upp sitt förakt för sina grannar, för alla medlemmar i FN, och för grundläggande standarder för acceptabelt beteende på världsarenan", rapporterar Reuters.

Även USA:s FN-ambassadör Nikki Haley kallar Nordkoreas uppskjutning "oacceptabel".

– De har brutit mot varenda resolution som FN:s säkerhetsråd har antagit, och därför anser jag att någonting allvarligt måste ske, säger hon utan att specificera vad hon syftar på, enligt nyhetsbyrån AFP.

Varningsmeddelanden skickades ut i tv och radio i Japan tidigt på tisdagsmorgonen lokal tid. Snabbtåg stoppades och larmet gick i högtalare i städer på Hokkaido, den nordligaste av Japans huvudöar, där invånarna uppmanades söka skydd.

Den nordkoreanska roboten sköts upp i riktning mot Stilla havet från en plats nära Nordkoreas huvudstad Pyongyang klockan 5.57.

Ayaka Nishijima, som bor på den norra delen av Japans största ö Honshu, väcktes av ett varningsmeddelande på mobiltelefonen.

"Jag känner mig inte alls förberedd. Även om vi får de här meddelandena undrar jag vart vi ska ta vägen. Vi har ingen källare eller skyddsrum, så det enda vi kan göra är att hålla oss borta från fönstren", skriver hon i ett meddelande till Reuters.

Japansk militär försökte inte skjuta ner roboten, som passerade över landet klockan 6.06 lokal tid. Den föll sönder i tre delar och slog ned i vattnet 118 mil öster Hokkaido, enligt det nationella tv-bolaget NHK. Då hade den flugit 270 mil, och nått en höjd av 55 mil, enligt sydkoreansk militär.

Japan har tidigare lovat att skjuta ner robotar som hotar landet.

– Vi kommer att anstränga oss till vårt yttersta för att beslutsamt skydda vårt folks liv, säger landets premiärminister Shinzo Abe.

EU fördömer Nordkoreas robottest. Utrikeschefen Federica Mogherini säger i ett uttalande att EU kommer att titta närmare på "ett lämpligt svar" i nära samråd med allierade, och i linje med säkerhetsrådets överläggningar.

Från kinesiskt håll kommer uttalanden om att spänningarna på Koreahalvön har "nått en brytpunkt". Även den ryska regeringen är "extremt oroad" av situationen i Nordkorea, rapporterar den statliga ryska nyhetsbyrån Ria Novosti.

USA:s nedrustningsambassadör Robert Wood kallar testet "ytterligare en provokation".

Nordkorea å sin sida anklagar USA för att driva situationen på Koreahalvön till ett "extremt explosivt tillstånd", och säger att regeringen i Pyongyang har all rätt att ta till hårda motmedel.

– Nu när USA öppet har visat sina fientliga intentioner mot Demokratiska folkrepubliken Korea, genom aggressiva gemensamma militärövningar trots upprepade varningar, har mitt land all anledning att svara med hårda motåtgärder i självförsvarssyfte, säger Nordkoreas ambassadör till FN i Genève, Han Tae Song.

– USA bör hållas ensamt ansvarigt för de katastrofala konsekvenser detta kommer att föra med sig, fortsätter han, enligt Reuters.

Demokratiska folkrepubliken Korea är Nordkoreas officiella namn.

Ett extrainsatt möte i FN:s säkerhetsråd hålls på tisdagen, efter påtryckningar från USA, Japan och Sydkorea.

I början av augusti röstade rådet enhälligt ja till nya tuffare sanktioner mot Nordkorea. De innebar bland annat ett totalt förbud för export av kol och järn till landet.

Enligt Japans försvarsminister Itsunori Onodera var tisdagens robot sannolikt en medeldistansrobot av samma typ som den som sköts upp i maj. Nordkorea har i sommar vid två tillfällen testat långdistansrobotar med kapacitet att nå USA.

Nordkorea har avfyrat en rad robotar tidigare som har slagit ned i vattnen utanför Japan. I lördags sköt Nordkorea upp vad som tros ha varit tre kortdistansrobotar som flög runt 25 mil i nordostlig riktning.

2009 sköts en robot upp från Nordkorea som passerade över Japan, utan att orsaka skador. Då sade diktaturen att det rörde sig om en satellituppskjutning, men USA, Sydkorea och Japan bedömde efteråt att det rörde sig om ett robottest.

TT
