Två döda vid protester mot Togos president


Togo. Två demonstranter dödades och 13 skadades när säkerhetsstyrkor öppnade eld för att skingra en demonstration i staden Sokodé i Togo mot den styrande Gnassingbé-dynastin. Minst tolv militärer har också skadats, uppger säkerhetsdepartementet.

Även i huvudstaden Lomé bröt protester ut. Där använde säkerhetsstyrkor tårgas för att skingra de protesterande.

Presidenten Faure Gnassingbé efterträdde sin far 2005, fadern hade då suttit 38 år vid makten. När sonen blev president utbröt kraftiga protester.

Nu har han och fadern sammanlagt suttit vid makten i Togo i 50 år, något som demonstranterna i Lomé tog fasta på när de i talkör ropade: "50 år är för lång tid!".

De tusentals demonstranterna krävde bland annat att en konstitutionell begränsning av antalet mandatperioder en president kan sitta återinförs. Den förre presidenten införde, efter protester, en sådan begränsning 1992.

TT-Reuters
