Peter Jihde  om sin obotliga sjukdom: ”Inget jag bett om”
JAN-OLOV ANDERSSON

För fyra år sedan drabbades TV 4-profilen Peter Jihde, 45, av diabetes. Hur livet sedan dess har förändrats berättar han om i boken ”Jihdes diabetes – en match för livet”.

– Genom resans gång fick jag veta att jag också är bipolär. En diagnos jag inte hade bett om. Men om jag skulle önska att bli av med någon av sjukdomarna, är det definitivt diabetesen, säger han till Nöjesbladet.
