Så krossades myten om Clark Olofsson


■ ■ Det finns vissa berättelser som är värda att berätta igen.

Brott som fortsätter att fascinera år efter år.

■ ■ Sommaren 2008 publicerade Aftonbladet ett antal bilagor där våra bästa skribenter berättade hela historien bakom de fall som skakat om Sverige.

■ ■ Nu presenterar vi dessa dessutom i en ny digital form, med poddar inlästa av Aftonbladets Kerstin Weigl.

■ ■ Först ut är berättelsen om Clark Olofsson, skriven av Aftonbladets Jan Helin.
