”Allt fler människor plågas av djävulen”


I fem delar granskar vi exorcismen i Norden.

Del 1: Lars vill driva djävulen ur dig

Del 2: ”Jag kände att jag hade en demon i mig” (Publiceras 17 juni)

Del 3: Prästernas bildbevis: ”Djävulen finns” (Publiceras 19 juni)

Del 4: Exorcisternas hemliga medhjälpare (Publiceras 21 juni)

Del 5: Svenska katolska kyrkan hänvisar till dansk exorcist (Publiceras 21 juni)
